name: Tests and Checks

on: push

jobs:
  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master
    with:
      languages: javascript
  docker:
    uses: lidofinance/linters/.github/workflows/docker.yml@master
  test:
    name: App tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Run jest
        run: yarn test
