---
name: CI dev

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - ".github/**"

jobs:
  main:
    runs-on: ubuntu-latest
    name: Build and deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Testnet deploy
        run: .github/dispatch_workflow.py
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          TARGET_REPO: "${{ secrets.TARGET_REPO }}"
          TARGET_WORKFLOW: "deploy_testnet_alertmanager_discord.yaml"
